export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const SIGNIN_OR_SIGNUP = 'SIGNIN_OR_SIGNUP';
export const SIGNIN_OR_SIGNUP_SUCCESS = 'SIGNIN_OR_SIGNUP_SUCCESS';
export const SIGNIN_OR_SIGNUP_FAILURE = 'SIGNIN_OR_SIGNUP_FAILURE';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';
