export const REQUEST_RECIPES = 'REQUEST_RECIPES';
export const REQUEST_RECIPES_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_RECIPES_FAILURE = 'REQUEST_RECIPES_FAILURE';
export const GET_NO_RECIPE = 'GET_NO_RECIPE';
